git:
  depth: 1
  submodules: false

language: rust
rust:
  - beta
  - stable


before_script:
  - rustup component add rustfmt
  - rustup component add clippy
script:
  - cargo fmt --all -- --check 
  - cargo clippy  # https://github.com/rust-lang/rust-clippy  #A collection of lints to catch common mistakes and improve your Rust code.
  - cargo build --all --verbose --workspace
  - cargo test --all --workspace