[package]
name = "rustlab"
version = "0.1.0"
authors = ["zhouxiaoshuai <zhouxiaoshuai@huya.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tempdir = "0.3.7"
