[package]
name = "dream"
version = "0.1.0"
authors = ["bidhan-a <bidhan619@gmail.com>"]
edition = "2018"

[dependencies]
csv = "1.1.3"
crossbeam = "0.7.3"
crossbeam-utils = "0.7.2"
log = "0.4.8"
chrono = "0.4.11"
uuid = { version = "0.8", features = ["v4"] }
avro-rs = "0.10.0"
serde = "1.0.114"

[dev-dependencies]
fern = "0.6.0"
