[package]
name = "pulsar"
version = "1.0.1"
edition = "2018"
authors = [
    "Colin Stearns <cstearns@developers.wyyerd.com>",
    "Kevin Stenerson <kstenerson@developers.wyyerd.com>",
    "Geoffroy Couprie <contact@geoffroycouprie.com>",
]

license = "MIT/Apache-2.0"
readme = "./README.md"
repository = "https://github.com/wyyerd/pulsar-rs"
documentation = "https://docs.rs/pulsar"
description = "Rust client for Apache Pulsar"
keywords = ["pulsar", "api", "client"]

[badges]
travis-ci = {repository = "wyyerd/pulsar-rs"}

[dependencies]
bytes = "0.5.0"
crc = "1.0.0"
futures = "0.3"
nom = "5.0.0"
prost = "0.6.0"
prost-derive = "0.6.0"
rand = "0.7"
chrono = "0.4.6"
futures-timer = "3.0"
log = "0.4.6"
url = "2.1"
regex = "1.1.7"
bit-vec = "0.6"
futures-io = "0.3"
native-tls = "0.2"
pem = "0.8"
tokio = { version = "0.2", features = ["rt-threaded", "blocking", "full"], optional = true }
tokio-util = { version = "0.3", features = ["codec"], optional = true }
tokio-native-tls = { version = "0.1", optional = true }
async-std = {version = "1.5", features = [ "attributes", "unstable" ], optional = true }
futures_codec = { version = "0.4", optional = true }
async-native-tls = { version = "0.3", optional = true }
lz4 = { version = "1.23", optional = true }
flate2 = { version = "1.0", optional = true }
zstd = { version = "0.5", optional = true }
snap = { version = "1.0", optional = true }

[dev-dependencies]
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
env_logger = "0.7"

[build-dependencies]
prost-build = "0.6.0"

[features]
default = [ "compression", "tokio-runtime", "async-std-runtime" ]
compression = [ "lz4", "flate2", "zstd", "snap" ]
tokio-runtime = [ "tokio", "tokio-util", "tokio-native-tls" ]
async-std-runtime = [ "async-std", "futures_codec", "async-native-tls" ]
