name: CI
# Continuous Integration

on:
  push:
    branches: [ master ]
    paths:
      - 'basic-exercises/**'
      - 'example-projects/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy
    - name: Run fmt check
      run: cargo fmt -- --check
    - name: Build
      run: cargo build --all-features --workspace --exclude third-party
    - name: Run tests
      run: cargo test --all-features --workspace  --exclude third-party
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic 
    
    - name: Install cargo-tarpaulin
      uses: actions-rs/install@v0.1
      with:
        crate: cargo-tarpaulin
        version: latest
        use-tool-cache: true
    - name: Run cargo-tarpaulin
      run: cargo tarpaulin --all-features --workspace  --exclude-files third-party/* --timeout 1200 --out Xml
    - name: Upload to codecov.io
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}  # not required for public repos